### ISSUE TITLE
release 8.0.29 to get the latest version before WebSocket bug

### ISSUE THREAD

**Issue by musketyr** [grails-plugins/grails-tomcat-plugin#15]
there is a bug in WebSocket in version 8.0.30 and later

https://bz.apache.org/bugzilla/show_bug.cgi?id=59014

which breaks Spring WebSocket support

https://jira.spring.io/browse/INT-3909

would be nice if I can use the version one before the bug was introduced (8.0.29)

**Comment by burtbeckwith** [comment]
fixed in 8.0.33 and 9.0.0.M4.1 (the Tomcat bug was resolved in 8.0.32)
