### ISSUE TITLE
using your own ssl keystore functionality is broken

### ISSUE THREAD

**Issue by edwardotis** [grails-plugins/grails-tomcat-plugin#18]
8.x branch
build ":tomcat:8.0.30" 
org.grails.plugins.tomcat.TomcatServer#TomcatServer

The truststore tries to configure itself if 'userKeystore' is set.
So, that looks wrong. (see below in the snippet)
	
	def userTruststore = getConfigParam("truststorePath")
		if (userKeystore) {

If by chance it's right to check that variable, then the bug becomes the missing system property documentation for the truststorePath and  truststorePassword.

End result. Cannot use your own cert or jks with the tomcat plugin. Server just times out with no error message.
The automatic one works, and the other methods to bring your own credentials fail.

	```
	def userKeystore = getConfigParam("keystorePath")
		if (userKeystore) {
			usingUserKeystore = true
			keystoreFile = new File(userKeystore.toString())
			keyPassword = getConfigParam("keystorePassword") ?: "changeit" // changeit is the keystore default
		}
		else {
			usingUserKeystore = false
			keystoreFile = getWorkDirFile("ssl/keystore")
			keyPassword = "123456"
		}

		def userTruststore = getConfigParam("truststorePath")
		if (userKeystore) {
			truststore = userTruststore
			trustPassword = getConfigParam("truststorePassword") ?: "changeit"
		}
		else {
			truststore = "${buildSettings.grailsWorkDir}/ssl/truststore"
			trustPassword = "123456"
		}
```

**Comment by burtbeckwith** [comment]
fixed in 8.0.33 and 9.0.0.M4.1
