### ISSUE TITLE
Versions above 7 do not load the ForkedTomcatCustomizer.

### ISSUE THREAD

**Issue by pcjericks** [grails-plugins/grails-tomcat-plugin#19]
I recently updated a grails app from tomcat 7 to 8 and discovered that my ForkedTomcatCustomizer was no longer getting loaded by the TomcatDevelopmentRunner.  

After some debugging, I discovered that the forkedClassLoader property was moved from the InlineExplodedTomcatServer to the TomcatDevelopmentRunner during 8.x development but it is used before it is assigned due to the TomcatDevelopmentRunner calling super which then invokes the InlineExplodedTomcatServer constructor which then call invokeCustomizer which then tries to load the ForkedTomcatCustomizer class with a null forkedClassLoader.

I fixed it locally by moving the forkedClassLoader property back to the InlineExplodedTomcatServer.

If my fix seems appropriate I can submit a pull request.

**Comment by bobbywarner** [comment]
Manually applied the fix to the 8.x branch (https://github.com/grails-plugins/grails-tomcat-plugin/commit/c898015a6deaaf7f1da4585333822e6fa018a002) and released version 8.0.50 of the plugin with this fix.
